build:
  version: "3.0"

accounts:
  message: "Welcome to Super Shopee related docker APIs "
  contactDetails:
    name: "Ravindra Nawale - Developer"
    email: "ravi.nawale@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
